/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.conexionOracle;
import Persistencia.experto;
import Persistencia.manejaColabora;
import Persistencia.manejaExperto;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame para la ventana Experto
 * Se utiliza trabajar graficamente con la tabla Experto
 * @author Pablo Caceres
 * @version 1.0
 */
public class ventanaExpertos extends javax.swing.JFrame {

   /**
 * Construstor
 * @param co conexionOracle
 * @param vP ventanaPrincipal
 * @throws SQLException excepcion base de datos
 */
    public ventanaExpertos(conexionOracle co,ventanaPrincipal vP) throws SQLException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);//hace que al cerrar no se termine el programa
        this.co = co;
        mExp=new manejaExperto(co);
        this.vP=vP;
        //para ajustar la tabla
        modeloTExpertos = new DefaultTableModel();
        JTable tExpertos = new JTable(modeloTExpertos);
        dibujarTablaExpertos();
        
        pideExpertos();

    }
    /**
     * Dibuja la Tabla Expertos en el JFrame
     */
    private void dibujarTablaExpertos() {

        tExpertos.setModel(modeloTExpertos);
        String[] columnasTabla = {"Código", "Nombre", "País", "Sexo", "Especialidad"};
        modeloTExpertos.setColumnIdentifiers(columnasTabla);
        // Para no permitir el redimensionamiento de las columnas con el ratón
        tExpertos.getTableHeader().setResizingAllowed(false);
        // Así se fija el ancho de las columnas
        tExpertos.getColumnModel().getColumn(0).setPreferredWidth(25);
        tExpertos.getColumnModel().getColumn(1).setPreferredWidth(140);
        tExpertos.getColumnModel().getColumn(2).setPreferredWidth(80);
        tExpertos.getColumnModel().getColumn(3).setPreferredWidth(8);
        tExpertos.getColumnModel().getColumn(4).setPreferredWidth(122);
    }
    /**
     * Rellena la tabla de experto con los datos de la base de datos
     * @param expertos lista con los experton a rellenar
     */
    private void rellenarTablaExpertos(ArrayList<experto> expertos) {
        Object[] columna = new Object[5];
        int numRegistros = expertos.size();
        for (int i = 0; i < numRegistros; i++) {
            columna[0] = expertos.get(i).getCodExperto();
            columna[1] = expertos.get(i).getNombre();
            columna[2] = expertos.get(i).getPais();
            columna[3] = expertos.get(i).getSexo();
            columna[4] = expertos.get(i).getEspecialidad();
            modeloTExpertos.addRow(columna);
        }
    }
    /**
     * Vacia la tabla de expertos
     */
    private void vaciarTablaExpertos() {
        while (modeloTExpertos.getRowCount() > 0) {
            modeloTExpertos.removeRow(0);
        }
    }
    /**
     * Pide los expertos a la base de datos y rellena la tabla
     * @throws SQLException excepcion de la base de datos
     */
    private void pideExpertos() throws SQLException {
        ArrayList<experto> lExp = mExp.listaExpertos();
        rellenarTablaExpertos(lExp);
    }
    /**
     * Pide los expertos que pertenece a un pais introducido en el jFrame
     * @throws SQLException excepcion de la base de datos
     */
    private void pideExpertosPorPais() throws SQLException {
        String paisSeleccionado = txtPais.getText();
        ArrayList<experto> lExp = mExp.listaExpertosPorPais(paisSeleccionado);
        rellenarTablaExpertos(lExp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        Error = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tExpertos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LetraSexo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NumSex = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("¡¡¡ERROR!!!");

        Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(172, 172, 172))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tExpertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tExpertos);

        jLabel1.setText("Pais");

        txtPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisActionPerformed(evt);
            }
        });

        jButton1.setText("Filtrar por pais");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Sexo");

        LetraSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LetraSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(NumSex, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumSex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(LetraSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisActionPerformed
    /**
     * dibuja los experto por el pais seleccionado en la tabla del JFrame
     * @param evt click del raton
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dibujarTablaExpertos();
        vaciarTablaExpertos();
        try {
            pideExpertosPorPais();
        } catch (SQLException ex) {
            Logger.getLogger(ventanaExpertos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Dibuja todos los expertos en la tabla del JFrame
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dibujarTablaExpertos();
        vaciarTablaExpertos();
        try {
            pideExpertos();
        } catch (SQLException ex) {
            Logger.getLogger(ventanaExpertos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Muestra la respuesta del numero de experto por el sexo introducido
     * @param evt Pulta intro al introducir el sexo
     */
    private void LetraSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraSexoActionPerformed
        try {
            int numSex=mExp.numSexo(LetraSexo.getText());
            if(LetraSexo.getText().equals("F"))
            NumSex.setText("Hay "+String.valueOf(numSex)+" mujeres");
            
            if(LetraSexo.getText().equals("M"))
            NumSex.setText("Hay "+String.valueOf(numSex)+" hombres");
            
            
        } catch (SQLException ex) {
            NumSex.setText("0");
            Error.setText(ex.getMessage());
            jDialog1.setSize(610,234);
            jDialog1.setVisible(true);
        }
        
    }//GEN-LAST:event_LetraSexoActionPerformed

    /**
     * Se utiliza para que cuando se cierre la ventana se abra la ventana principal
     */
    @Override
    public void dispose(){//metodo del boton cerrar
        vP.setVisible(true);
        super.dispose();
    }
    
    
    private void ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorActionPerformed
/**
     * Lo utilizaremos para guardar la conexionOracle
     */
    private final conexionOracle co;
    /**
     * Lo utilizaremos para poder trabajar con la tabla de experto en el frame
     */
    private DefaultTableModel modeloTExpertos;
    /**
     * Lo utilizaremos para trabajar con manejarExperto
     */
    private manejaExperto mExp;
    /**
     * Lo utilizaremos para trabajar con manejaColabora
     */
    private manejaColabora mCol;
    /**
     * Lo utilizaremos guardar la ventana principal para volver cuando
     * se cierra la ventanaExperto
     */
    private ventanaPrincipal vP;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Error;
    private javax.swing.JTextField LetraSexo;
    private javax.swing.JLabel NumSex;
    private javax.swing.JTable Table2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tExpertos;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
